# Generated by Django 2.1.3 on 2018-11-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido1', models.CharField(default='', max_length=300)),
                ('titulo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
