# Generated by Django 2.1.3 on 2018-11-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='titulo',
            field=models.CharField(default='', max_length=25),
        ),
    ]
