# Generated by Django 2.1.1 on 2018-12-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_auto_20181124_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='capitulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenido.Capitulo'),
        ),
    ]
