# Generated by Django 2.1.4 on 2018-12-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_auto_20181216_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='imagen',
            field=models.CharField(default='', max_length=500),
        ),
    ]
