# Generated by Django 2.1.4 on 2018-12-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_auto_20181217_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='contenido2',
            field=models.CharField(default='', max_length=300),
        ),
    ]
